### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zacaway** [Fmstrat/samba-domain#3]
Hello,

This looks like a useful project for me (I'm trying to setup a local AD server for testing purposes), but I'm not sure if I am permitted to use it.  Would you be kind enough to add a License file please?  [GitHub guidelines](https://github.com/github/choosealicense.com/blob/gh-pages/no-permission.md) suggest no license means nobody can use it.

Thank you,
Mike

**Comment by Fmstrat** [comment]
Sure, I'll probably slap a GPL license on it but need to read up on the options. Out of pure curiosity, since you're asking about licensing I'm guessing it's business use. How are you leveraging it? And any feedback?

I know the next thing I will do is migrate the OpenVPN outside of the container and provide compose references for 2+ site connections instead of the 2 site connection that's built in. But beyond that, I haven't heard from any users.

**Comment by zacaway** [comment]
Great, thank you.  I'm working on an ERP-type application for internal business use, with usual LAMP stack.  Part of it connects to a corporate ActiveDirectory server (over LDAP) to match logins in the application with corporate accounts and find out what AD groups a user belongs to (which is then used to control access to features in the application).

What I'm looking for is a simple way to run an AD server on my linux dev machine, so that I can test this integration locally before deploying.  (Then I can use samba-tool to add test users and groups, and change group membership, and test it works correctly).

This docker image seems to work well for this use - the only problem I found is that it has samba 4.3 (via Ubuntu xenial) which has [this bug](https://bugzilla.samba.org/show_bug.cgi?id=10493) which affects the application I'm working on.  The bug is fixed in 4.4 so I tried just switching your Dockerfile to bionic and that seemed to work correctly.  Is that something you would consider updating?

**Comment by CorneliusHuber** [comment]
I would also like to use this in a corporate environment. If you added a license I could use your project. Planned changes would be to 
1) Upgrade to Ubuntu 18.04
2) Streamline the process of using a vpn
3) Add a few compatibility configurations for Linux (Group IDs and so on)
4) A lot of code cleanup (to enable other people who are not so invested to linux to read it)
If you add a license very fast (best case: tomorrow) that would be very nice. Otherwise I will not be able to use your code as a starting point.

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/samba-domain/commit/49d35884d6495fb9813c76b3827f155eb97b7195
